language: julia
os:
  - linux
sudo: required
dist: trusty
julia:
  - 0.4
  - nightly
notifications:
  email: false
after_success:
  - julia -e 'cd(Pkg.dir("LibArchive")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
